// Code generated by coz. DO NOT EDIT.

/**
 * Html of the-components
 * @module the-html
 */
'use strict';

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");

Object.defineProperty(exports, "__esModule", {
  value: true
});
Object.defineProperty(exports, "TheHtml", {
  enumerable: true,
  get: function get() {
    return _TheHtml.default;
  }
});
Object.defineProperty(exports, "TheHtmlStyle", {
  enumerable: true,
  get: function get() {
    return _TheHtmlStyle.default;
  }
});

var _TheHtml = _interopRequireDefault(require("./TheHtml"));

var _TheHtmlStyle = _interopRequireDefault(require("./TheHtmlStyle"));
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImluZGV4LmpzeCJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTs7QUFDQTs7OztBQUlBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQUVBOztBQUNBIiwic291cmNlUm9vdCI6Ii4uL2xpYiIsInNvdXJjZXNDb250ZW50IjpbIi8vIENvZGUgZ2VuZXJhdGVkIGJ5IGNvei4gRE8gTk9UIEVESVQuXG4vKipcbiAqIEh0bWwgb2YgdGhlLWNvbXBvbmVudHNcbiAqIEBtb2R1bGUgdGhlLWh0bWxcbiAqL1xuJ3VzZSBzdHJpY3QnXG5cbmltcG9ydCBUaGVIdG1sIGZyb20gJy4vVGhlSHRtbCdcbmltcG9ydCBUaGVIdG1sU3R5bGUgZnJvbSAnLi9UaGVIdG1sU3R5bGUnXG5cbmV4cG9ydCB7XG4gIFRoZUh0bWwsXG4gIFRoZUh0bWxTdHlsZSxcbn1cblxuIl19